services:
  test:
    build: .
    ports:
      - 8082:80
    environment:
      - PORT=80
      - PHP7_disable_functions=exec
      - PHP7_display_errors=On
      - PHP7_error_reporting=On
      - PHP7_max_execution_time=60
      - PHP7_max_input_time=60
      - PHP7_max_input_vars=300
      - PHP7_max_post_size=100M
      - PHP7_memory_limit=1024M
      - PHP7_post_max_size=100M
      - PHP7_short_open_tag=On
      - PHP7_upload_max_filesize=100M
